### ISSUE TITLE
Hello Maxim, Wanted to let you know wrong paths in CSS

### ISSUE THREAD

**Issue by markudevelop** [uzumaxy/meteor-jstree#1]
The images do not work. It's looking for them at `url("packages/uzumaxy_jstree/uzumaxy_jstree/css/32px.png")`

changing style.css to specfic `/packages/uzumaxy_jstree/uzumaxy_jstree/css/32px.png` make it work or adding all images to `css` folder

**Comment by eterey** [comment]
Thanks. Seems, I fixed this bug.
